/// THIS FILE IS AUTOGENERATED BY BUILD.RS
/// TO ADD NEW UNITS, ADD A NEW FILE TO THE UNITS DIRECTORY
pub static CARDS: &[&str] = &[
    r#"{"name":"Silly","emoji":"🤗","cost":165,"health":90,"power":20,"size":1.0,"speed":1.0,"attack_type":"Single"}"#,
    r#"{"name":"Ninja","emoji":"🥷","cost":200,"health":100,"power":20,"size":1.0,"speed":1.4,"attack_type":"Single"}"#,
    r#"{"name":"EXPLOSIVE","emoji":"🧨","cost":1000,"health":1,"power":9999,"size":1.2,"speed":10.0,"attack_type":"Area"}"#,
    r#"{"name":"Golem","emoji":"🗿","cost":2500,"health":1500,"power":55,"size":2.5,"speed":0.2,"attack_type":"Area"}"#,
    r#"{"name":"Snowman","emoji":"⛄","cost":340,"health":175,"power":30,"size":1.0,"speed":0.85,"attack_type":"Single"}"#,
    r#"{"name":"Sneaker","emoji":"🫥","cost":75,"health":40,"power":25,"size":0.99,"speed":1.5,"attack_type":"Single"}"#,
    r#"{"name":"Cowboy","emoji":"🤠","cost":150,"health":85,"power":35,"size":1.1,"speed":0.9,"attack_type":"Single"}"#,
    r#"{"name":"Super Hero","emoji":"🦸","cost":2555,"health":1000,"power":60,"size":1.0,"speed":1.25,"attack_type":"Area"}"#,
    r#"{"name":"Boar","emoji":"🐗","cost":400,"health":120,"power":40,"size":1.2,"speed":1.2,"attack_type":"Single"}"#,
    r#"{"name":"Nerd","emoji":"🤓","cost":314,"health":200,"power":15,"size":0.88,"speed":0.67,"attack_type":"Single"}"#,
    r#"{"name":"Melted","emoji":"🫠","cost":350,"health":120,"power":20,"size":1.0,"speed":0.875,"attack_type":"Area"}"#,
    r#"{"name":"Snail","emoji":"🐌","cost":60,"health":100,"power":10,"size":0.3,"speed":0.1,"attack_type":"Area"}"#,
    r#"{"name":"ANGRY","emoji":"😡","cost":150,"health":50,"power":50,"size":1.1,"speed":1.5,"attack_type":"Single"}"#,
    r#"{"name":"Smiley","emoji":"🙂","cost":75,"health":75,"power":15,"size":1.0,"speed":1.0,"attack_type":"Single"}"#,
    r#"{"name":"Boomer","emoji":"🤯","cost":550,"health":1,"power":150,"size":1.0,"speed":2.5,"attack_type":"Area"}"#,
    r#"{"name":"Alien","emoji":"👽","cost":500,"health":135,"power":22,"size":0.7,"speed":1.8,"attack_type":"Area"}"#,
];
