/// THIS FILE IS AUTOGENERATED BY BUILD.RS
/// TO ADD NEW UNITS, ADD A NEW FILE TO THE UNITS DIRECTORY
pub static CARDS: &[&str] = &[
    r#"{"name":"Cowboy","emoji":"🤠","cost":150,"health":85,"power":35,"size":1.1,"speed":0.9,"attack_type":"Single"}"#,
    r#"{"name":"Smiley","emoji":"🙂","cost":75,"health":75,"power":15,"size":1.0,"speed":1.0,"attack_type":"Single"}"#,
];
